version: '3'

vars:
  PKG: ./...
  COVERAGE_FILE: coverage.out
  FAILFAST: -failfast
  TIMEOUT: 10m

tasks:
  default:
    cmds:
      - task: generate
      - task: lint
      - task: tests

  tests:
    cmds:
      - go test -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile {{.COVERAGE_FILE}} -covermode atomic -timeout {{.TIMEOUT}} {{.PKG}}

  lint:
    cmds:
    - golangci-lint run -v --fix {{.PKG}}

  generate:
    cmds:
      - go generate {{.PKG}}

  bench:
    cmds:
      - go test -test.bench=. {{.PKG}}
