version: '3'

vars:
  PKG: ./...
  COVERAGE_FILE: coverage.out
  FAILFAST: -failfast
  TIMEOUT: 10m

tasks:
  default:
    cmds:
      - task: generate_parser
      - task: lint
      - task: tests

  tests:
    cmds:
      - go test -v {{.FAILFAST}} -coverpkg {{.PKG}} -coverprofile {{.COVERAGE_FILE}} -covermode atomic -timeout {{.TIMEOUT}} {{.PKG}}

  lint:
    cmds:
    - golangci-lint run -v --fix {{.PKG}}

  generate_parser:
    env:
      ANTLR_VERSION: "4.10.1"
      CLASSPATH: ".:/usr/local/lib/antlr-$ANLR_VERSION-complete.jar:$CLASSPATH"
    cmds:
      - cd /usr/local/lib && sudo curl --continue-at - https://www.antlr.org/download/antlr-$ANTLR_VERSION-complete.jar -O
      - rm -rf ./script/parser
      - cd script && java -Xmx500M -cp "/usr/local/lib/antlr-$ANTLR_VERSION-complete.jar:$CLASSPATH" org.antlr.v4.Tool -Dlanguage=Go -o parser NumScript.g4

  bench:
    cmds:
      - go test -test.bench=. {{.PKG}}
