name: Main
on:
  push:
    branches:
      - main
jobs:
  Test:
    uses: numary/gh-workflows/.github/workflows/golang-test.yml@main

  Lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main
